; every example is checked as part of `dune test`

(rule
 (alias runtest)
 (deps church_bool.mtt %{bin:mtt})
 (action
  (run mtt church_bool.mtt)))

(rule
 (alias runtest)
 (deps leibniz.mtt %{bin:mtt})
 (action
  (run mtt leibniz.mtt)))

(rule
 (alias runtest)
 (deps church_nat.mtt %{bin:mtt})
 (action
  (run mtt church_nat.mtt)))

(rule
 (alias runtest)
 (deps logic.mtt %{bin:mtt})
 (action
  (run mtt logic.mtt)))

(rule
 (alias runtest)
 (deps unit.mtt %{bin:mtt})
 (action
  (run mtt unit.mtt)))

(rule
 (alias runtest)
 (deps empty.mtt %{bin:mtt})
 (action
  (run mtt empty.mtt)))
