name: Format

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4"
          dune-cache: true

      - name: Check formatting
        uses: ocaml/setup-ocaml/lint-fmt@v3
